name = "FastHartleyTransform"
uuid = "e0605d58-1a4b-427b-8ab9-d16fed775e83"
authors = ["Kazunori Akiyama"]
version = "0.1.0"

[deps]
AbstractFastHartleyTransforms = "19a999c2-4b91-4a95-a5ef-9640c9e909f0"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[weakdeps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"

[extensions]
FastHartleyTransformCUDAExt = ["CUDA"]

[compat]
AbstractFastHartleyTransforms = "0.1"
CUDA = "5"
FFTW = "1"
julia = "1.10"

[extras]
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "StableRNGs"]
